name: Deploy Development

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          USERNAME: ${{ secrets.DEV_USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.DEV_SSHKEY }}
          script: cd ${{ secrets.DEV_PATH }} && ls && git pull && docker-compose up --build -d
